### ISSUE TITLE
about data read

### ISSUE THREAD

**Issue by wanboyang** [Ohraincu/JDNet#1]
Thanks for opening source.
```
 `def __getitem__(self, idx):
        file_name = self.mat_files[idx % self.file_num]
        img_file = os.path.join(self.root_dir, file_name)
        img_pair = cv2.imread(img_file).astype(np.float32) / 255
        h, ww, c = img_pair.shape
        w = int(ww / 2)
        #h_8=h%8
        #w_8=w%8
        O = np.transpose(img_pair[:, w:], (2, 0, 1))
        B = np.transpose(img_pair[:, :w], (2, 0, 1))
        sample = {'O': O, 'B': B}

        return sample` 
```

in the dataset.py[https://github.com/Ohraincu/JDNet/blob/master/code/base/rain100L/config/dataset.py](url).
 It seems that rainy images and their unrainy ones are concatenated in second axis, Is it correct?

**Comment by Ohraincu** [comment]
Yes, our synthetic datasets are all inputed in pairs, which is mentioned in 'Supplement to settings.py' (from readme.md).

**Comment by wanboyang** [comment]
Thanks for timely reply.
