### ISSUE TITLE
the complete train and test cod of JDNet

### ISSUE THREAD

**Issue by xiaomei-0217** [Ohraincu/JDNet#3]
Your research on JDNet is of great help to my research work, and I hope to get a complete model training and test code, Thank you very much!

**Comment by Ohraincu** [comment]
Thank you for your appreciation.

Pretrained model can be got on GoogleDrive or BaiduYun:
BaiduYun: https://pan.baidu.com/s/1MHVnTTN-kjeDQ-x9m_zr0Q  (password:9sbj) 
GoogleDrive: https://drive.google.com/drive/folders/1rzidCqbhgnKEGNOgFLqSUynhux4SfURI

If you want to test, you can read our readme.md
You can get the corresponding numerical results after running eval.py.
If the visual results on datasets need to be observed, the show.py can be run.
